language: python
python:
  - "3.6"

services:
  - docker

before_script: 
  - pip install docker-compose
  - pip install codecov
  - bash generateCerts.sh
  - python genproto.py
  - python run.py &

script:
  - coverage run --source=test -m pytest && coverage report

after_success:
- coveralls